// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import { __loadObject as __loadCoreObject } from "./sdk/loader.gen.js"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { BiomeProject, BiomeProjects, Biomejs } from "./src/index"

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}

function rebuildBiomeProject(state: any): BiomeProject {
  const __obj = Object.assign(Object.create(BiomeProject.prototype), state ?? {})
  if (state) {
    if (state["environment"] !== undefined && state["environment"] !== null) {
      __obj["environment"] = (state["environment"] as any[]).map((__v) => __v)
    }
    if (state["installFlags"] !== undefined && state["installFlags"] !== null) {
      __obj["installFlags"] = (state["installFlags"] as any[]).map((__v) => __v)
    }
  }
  return __obj
}

async function serializeBiomeProject(__obj: BiomeProject): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["environment"] !== undefined && (__obj as any)["environment"] !== null) {
    __state["environment"] = await Promise.all(((__obj as any)["environment"] as any[]).map(async (__v) => __v))
  }
  if ((__obj as any)["installFlags"] !== undefined && (__obj as any)["installFlags"] !== null) {
    __state["installFlags"] = await Promise.all(((__obj as any)["installFlags"] as any[]).map(async (__v) => __v))
  }
  return __state
}

function rebuildBiomeProjects(state: any): BiomeProjects {
  const __obj = Object.assign(Object.create(BiomeProjects.prototype), state ?? {})
  if (state) {
    if (state["environment"] !== undefined && state["environment"] !== null) {
      __obj["environment"] = (state["environment"] as any[]).map((__v) => __v)
    }
    if (state["installFlags"] !== undefined && state["installFlags"] !== null) {
      __obj["installFlags"] = (state["installFlags"] as any[]).map((__v) => __v)
    }
    if (state["paths"] !== undefined && state["paths"] !== null) {
      __obj["paths"] = (state["paths"] as any[]).map((__v) => __v)
    }
  }
  return __obj
}

async function serializeBiomeProjects(__obj: BiomeProjects): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["environment"] !== undefined && (__obj as any)["environment"] !== null) {
    __state["environment"] = await Promise.all(((__obj as any)["environment"] as any[]).map(async (__v) => __v))
  }
  if ((__obj as any)["installFlags"] !== undefined && (__obj as any)["installFlags"] !== null) {
    __state["installFlags"] = await Promise.all(((__obj as any)["installFlags"] as any[]).map(async (__v) => __v))
  }
  if ((__obj as any)["paths"] !== undefined && (__obj as any)["paths"] !== null) {
    __state["paths"] = await Promise.all(((__obj as any)["paths"] as any[]).map(async (__v) => __v))
  }
  return __state
}

function rebuildBiomejs(state: any): Biomejs {
  const __obj = Object.assign(Object.create(Biomejs.prototype), state ?? {})
  if (state) {
    if (state["environment"] !== undefined && state["environment"] !== null) {
      __obj["environment"] = (state["environment"] as any[]).map((__v) => __v)
    }
    if (state["installFlags"] !== undefined && state["installFlags"] !== null) {
      __obj["installFlags"] = (state["installFlags"] as any[]).map((__v) => __v)
    }
  }
  return __obj
}

async function serializeBiomejs(__obj: Biomejs): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["environment"] !== undefined && (__obj as any)["environment"] !== null) {
    __state["environment"] = await Promise.all(((__obj as any)["environment"] as any[]).map(async (__v) => __v))
  }
  if ((__obj as any)["installFlags"] !== undefined && (__obj as any)["installFlags"] !== null) {
    __state["installFlags"] = await Promise.all(((__obj as any)["installFlags"] as any[]).map(async (__v) => __v))
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  mod = mod.withDescription("A BiomeJS toolchain to execute Biome on a JavaScript project.")
  let obj_BiomeProject = dag.typeDef().withObject("BiomeProject", { description: "A Biome project, rooted at a workspace-relative directory holding a root\nBiome configuration.", sourceMap: dag.sourceMap("src/index.ts", 443, 14) })
  obj_BiomeProject = obj_BiomeProject.withFunction(dag.function_("fix", dag.typeDef().withObject("Changeset")).withDescription("Apply Biome's safe fixes to this project and return the changes.\n\nThe changes are rooted at the caller's working directory, where the CLI\napplies them: a project below it is placed at its relative path, and an\nenclosing project contributes only the working directory's subtree.\nFixes are returned even when diagnostics Biome cannot fix remain.").withSourceMap(dag.sourceMap("src/index.ts", 498, 8)).withArg("ws", dag.typeDef().withObject("Workspace"), { sourceMap: dag.sourceMap("src/index.ts", 499, 3) }).withArg("files", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Files to fix, relative to the project root.", sourceMap: dag.sourceMap("src/index.ts", 500, 3) }).withArg("fixFilter", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Patterns, relative to the project root, of files to include in the changeset. Empty includes every file Biome fixed.", sourceMap: dag.sourceMap("src/index.ts", 501, 3) }))
  obj_BiomeProject = obj_BiomeProject.withFunction(dag.function_("lint", dag.typeDef().withKind(TypeDefKind.VoidKind).withOptional(true)).withDescription("Lint this project.").withSourceMap(dag.sourceMap("src/index.ts", 477, 8)).withArg("ws", dag.typeDef().withObject("Workspace"), { sourceMap: dag.sourceMap("src/index.ts", 477, 13) }).withCheck())
  obj_BiomeProject = obj_BiomeProject.withField("path", dag.typeDef().withKind(TypeDefKind.StringKind), { description: "Project root, relative to the workspace.", sourceMap: dag.sourceMap("src/index.ts", 448, 2) })
  obj_BiomeProject = obj_BiomeProject.withConstructor(dag.function_("", obj_BiomeProject).withArg("path", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 459, 3) }).withArg("baseImageAddress", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 460, 3) }).withArg("packageManager", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 461, 3) }).withArg("installFlags", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)), { sourceMap: dag.sourceMap("src/index.ts", 462, 3) }).withArg("environment", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)), { sourceMap: dag.sourceMap("src/index.ts", 463, 3) }))
  mod = mod.withObject(obj_BiomeProject)
  let obj_BiomeProjects = dag.typeDef().withObject("BiomeProjects", { description: "Biome projects in a workspace, keyed by the directory of their root Biome\nconfiguration.", sourceMap: dag.sourceMap("src/index.ts", 811, 14) }).withCollection().withCollectionGet("project")
  obj_BiomeProjects = obj_BiomeProjects.withFunction(dag.function_("lint", dag.typeDef().withKind(TypeDefKind.VoidKind).withOptional(true)).withDescription("Lint the selected Biome projects.").withSourceMap(dag.sourceMap("src/index.ts", 859, 8)).withArg("ws", dag.typeDef().withObject("Workspace"), { sourceMap: dag.sourceMap("src/index.ts", 859, 13) }).withCheck())
  obj_BiomeProjects = obj_BiomeProjects.withFunction(dag.function_("project", dag.typeDef().withObject("BiomeProject")).withDescription("The Biome project rooted at path.").withSourceMap(dag.sourceMap("src/index.ts", 844, 2)).withArg("path", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 844, 10) }))
  obj_BiomeProjects = obj_BiomeProjects.withField("paths", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)), { description: "Project root paths.", sourceMap: dag.sourceMap("src/index.ts", 816, 2) }).withCollectionKeys("paths")
  obj_BiomeProjects = obj_BiomeProjects.withConstructor(dag.function_("", obj_BiomeProjects).withArg("paths", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)), { sourceMap: dag.sourceMap("src/index.ts", 827, 3) }).withArg("baseImageAddress", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 828, 3) }).withArg("packageManager", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 829, 3) }).withArg("installFlags", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)), { sourceMap: dag.sourceMap("src/index.ts", 830, 3) }).withArg("environment", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)), { sourceMap: dag.sourceMap("src/index.ts", 831, 3) }))
  mod = mod.withObject(obj_BiomeProjects)
  let obj_Biomejs = dag.typeDef().withObject("Biomejs", { sourceMap: dag.sourceMap("src/index.ts", 877, 14) })
  obj_Biomejs = obj_Biomejs.withFunction(dag.function_("projects", dag.typeDef().withObject("BiomeProjects")).withDescription("Biome projects at or below the working directory, keyed by project root.").withSourceMap(dag.sourceMap("src/index.ts", 916, 8)).withArg("ws", dag.typeDef().withObject("Workspace"), { sourceMap: dag.sourceMap("src/index.ts", 916, 17) }))
  obj_Biomejs = obj_Biomejs.withConstructor(dag.function_("", obj_Biomejs).withArg("baseImageAddress", dag.typeDef().withKind(TypeDefKind.StringKind), { defaultValue: JSON.stringify("node:25-alpine@sha256:f4769ca6eeb6ebbd15eb9c8233afed856e437b75f486f7fccaa81d7c8ad56007") as string & { __JSON: never }, description: "Base image for Biome containers. It must provide Node.js and npm.", sourceMap: dag.sourceMap("src/index.ts", 890, 3) }).withArg("packageManager", dag.typeDef().withKind(TypeDefKind.StringKind), { defaultValue: JSON.stringify("") as string & { __JSON: never }, description: "Package manager that installs dependencies: npm, yarn, pnpm or bun.\nEmpty detects it from package.json's packageManager field, else the\nlockfile, else npm.", sourceMap: dag.sourceMap("src/index.ts", 896, 3) }).withArg("installFlags", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Extra arguments for the install command, e.g. [\"--ignore-scripts\"].", sourceMap: dag.sourceMap("src/index.ts", 900, 3) }).withArg("environment", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Environment variables for Biome, as KEY=VALUE.", sourceMap: dag.sourceMap("src/index.ts", 904, 3) }))
  mod = mod.withObject(obj_Biomejs)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "BiomeProject": {
      switch (fnName) {

        case "": {
          const __arg_path = args["path"] === undefined || args["path"] === null ? args["path"] : args["path"]
          const __arg_baseImageAddress = args["baseImageAddress"] === undefined || args["baseImageAddress"] === null ? args["baseImageAddress"] : args["baseImageAddress"]
          const __arg_packageManager = args["packageManager"] === undefined || args["packageManager"] === null ? args["packageManager"] : args["packageManager"]
          const __arg_installFlags = args["installFlags"] === undefined || args["installFlags"] === null ? args["installFlags"] : (args["installFlags"] as any[]).map((__v) => __v)
          const __arg_environment = args["environment"] === undefined || args["environment"] === null ? args["environment"] : (args["environment"] as any[]).map((__v) => __v)
          const __result = await new BiomeProject(__arg_path, __arg_baseImageAddress, __arg_packageManager, __arg_installFlags, __arg_environment) as unknown as BiomeProject
          return await serializeBiomeProject(__result)
        }

        case "fix": {
          const __parent = rebuildBiomeProject(parentJson)
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __arg_files = args["files"] === undefined || args["files"] === null ? args["files"] : (args["files"] as any[]).map((__v) => __v)
          const __arg_fixFilter = args["fixFilter"] === undefined || args["fixFilter"] === null ? args["fixFilter"] : (args["fixFilter"] as any[]).map((__v) => __v)
          const __result = await __parent.fix(__arg_ws, __arg_files, __arg_fixFilter)
          return await (__result).id()
        }

        case "lint": {
          const __parent = rebuildBiomeProject(parentJson)
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __result = await __parent.lint(__arg_ws)
          return __result
        }
        default:
          throw new Error(`unknown function ${fnName} on BiomeProject`)
      }
    }
    case "BiomeProjects": {
      switch (fnName) {

        case "": {
          const __arg_paths = args["paths"] === undefined || args["paths"] === null ? args["paths"] : (args["paths"] as any[]).map((__v) => __v)
          const __arg_baseImageAddress = args["baseImageAddress"] === undefined || args["baseImageAddress"] === null ? args["baseImageAddress"] : args["baseImageAddress"]
          const __arg_packageManager = args["packageManager"] === undefined || args["packageManager"] === null ? args["packageManager"] : args["packageManager"]
          const __arg_installFlags = args["installFlags"] === undefined || args["installFlags"] === null ? args["installFlags"] : (args["installFlags"] as any[]).map((__v) => __v)
          const __arg_environment = args["environment"] === undefined || args["environment"] === null ? args["environment"] : (args["environment"] as any[]).map((__v) => __v)
          const __result = await new BiomeProjects(__arg_paths, __arg_baseImageAddress, __arg_packageManager, __arg_installFlags, __arg_environment) as unknown as BiomeProjects
          return await serializeBiomeProjects(__result)
        }

        case "lint": {
          const __parent = rebuildBiomeProjects(parentJson)
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __result = await __parent.lint(__arg_ws)
          return __result
        }

        case "project": {
          const __parent = rebuildBiomeProjects(parentJson)
          const __arg_path = args["path"] === undefined || args["path"] === null ? args["path"] : args["path"]
          const __result = await __parent.project(__arg_path)
          return await serializeBiomeProject(__result)
        }
        default:
          throw new Error(`unknown function ${fnName} on BiomeProjects`)
      }
    }
    case "Biomejs": {
      switch (fnName) {

        case "": {
          const __arg_baseImageAddress = args["baseImageAddress"]
          const __arg_packageManager = args["packageManager"]
          const __arg_installFlags = args["installFlags"] === undefined || args["installFlags"] === null ? args["installFlags"] : (args["installFlags"] as any[]).map((__v) => __v)
          const __arg_environment = args["environment"] === undefined || args["environment"] === null ? args["environment"] : (args["environment"] as any[]).map((__v) => __v)
          const __result = await new Biomejs(__arg_baseImageAddress, __arg_packageManager, __arg_installFlags, __arg_environment) as unknown as Biomejs
          return await serializeBiomejs(__result)
        }

        case "projects": {
          const __parent = rebuildBiomejs(parentJson)
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __result = await __parent.projects(__arg_ws)
          return await serializeBiomeProjects(__result)
        }
        default:
          throw new Error(`unknown function ${fnName} on Biomejs`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})