// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import { __loadObject as __loadCoreObject } from "./sdk/loader.gen.js"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Biomejs } from "./src/index"

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}

function rebuildBiomejs(state: any): Biomejs {
  const __obj = Object.assign(Object.create(Biomejs.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
    if (state["ws"] !== undefined && state["ws"] !== null) {
      __obj["ws"] = __loadCoreObject(state["ws"], "Workspace")
    }
  }
  return __obj
}

async function serializeBiomejs(__obj: Biomejs): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  if ((__obj as any)["ws"] !== undefined && (__obj as any)["ws"] !== null) {
    __state["ws"] = await ((__obj as any)["ws"]).id()
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  mod = mod.withDescription("A BiomeJS toolchain to execute Biome on a JavaScript project.")
  let obj_Biomejs = dag.typeDef().withObject("Biomejs", { sourceMap: dag.sourceMap("src/index.ts", 17, 14) })
  obj_Biomejs = obj_Biomejs.withFunction(dag.function_("fix", dag.typeDef().withObject("Changeset")).withDescription("Fix lint issue and return a changeset of the result.").withSourceMap(dag.sourceMap("src/index.ts", 72, 8)).withArg("files", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Files to apply fix on, relative to the client's working directory.", sourceMap: dag.sourceMap("src/index.ts", 73, 3) }).withArg("fixFilter", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Patterns to select files to include in the changeset.", sourceMap: dag.sourceMap("src/index.ts", 74, 3) }))
  obj_Biomejs = obj_Biomejs.withFunction(dag.function_("lint", dag.typeDef().withKind(TypeDefKind.VoidKind).withOptional(true)).withDescription("Lint the source code.").withSourceMap(dag.sourceMap("src/index.ts", 58, 8)).withArg("files", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { description: "Files to lint, relative to the client's working directory.", sourceMap: dag.sourceMap("src/index.ts", 58, 13) }).withCheck())
  obj_Biomejs = obj_Biomejs.withFunction(dag.function_("path", dag.typeDef().withKind(TypeDefKind.StringKind)).withDescription("Path of the client's working directory, relative to the workspace root.").withSourceMap(dag.sourceMap("src/index.ts", 44, 8)))
  obj_Biomejs = obj_Biomejs.withConstructor(dag.function_("", obj_Biomejs).withArg("ws", dag.typeDef().withObject("Workspace"), { sourceMap: dag.sourceMap("src/index.ts", 25, 3) }).withArg("baseImageAddress", dag.typeDef().withKind(TypeDefKind.StringKind), { defaultValue: JSON.stringify("node:25-alpine@sha256:f4769ca6eeb6ebbd15eb9c8233afed856e437b75f486f7fccaa81d7c8ad56007") as string & { __JSON: never }, description: "The base image to use.\n\nThis assume biome will run in a node container using npm\nas package manager.", sourceMap: dag.sourceMap("src/index.ts", 33, 3) }))
  mod = mod.withObject(obj_Biomejs)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Biomejs": {
      switch (fnName) {

        case "": {
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __arg_baseImageAddress = args["baseImageAddress"]
          const __result = await new Biomejs(__arg_ws, __arg_baseImageAddress) as unknown as Biomejs
          return await serializeBiomejs(__result)
        }

        case "fix": {
          const __parent = rebuildBiomejs(parentJson)
          const __arg_files = args["files"] === undefined || args["files"] === null ? args["files"] : (args["files"] as any[]).map((__v) => __v)
          const __arg_fixFilter = args["fixFilter"] === undefined || args["fixFilter"] === null ? args["fixFilter"] : (args["fixFilter"] as any[]).map((__v) => __v)
          const __result = await __parent.fix(__arg_files, __arg_fixFilter)
          return await (__result).id()
        }

        case "lint": {
          const __parent = rebuildBiomejs(parentJson)
          const __arg_files = args["files"] === undefined || args["files"] === null ? args["files"] : (args["files"] as any[]).map((__v) => __v)
          const __result = await __parent.lint(__arg_files)
          return __result
        }

        case "path": {
          const __parent = rebuildBiomejs(parentJson)
          const __result = await __parent.path()
          return __result
        }
        default:
          throw new Error(`unknown function ${fnName} on Biomejs`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})