/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context, BaseClient } from "@dagger.io/dagger"
import { dag as __dag } from "@dagger.io/dagger"
import {
  Changeset,
  Check,
  Workspace
} from "@dagger.io/dagger"
import type {
  ID
} from "@dagger.io/dagger"


export type BiomejsFixOpts = {
  /**
   * Files to apply fix on, relative to the client's working directory.
   */
  files?: string[] // biomejs (../src/index.ts:73:3)

  /**
   * Patterns to select files to include in the changeset.
   */
  fixFilter?: string[] // biomejs (../src/index.ts:74:3)
}

export type BiomejsLintOpts = {
  /**
   * Files to lint, relative to the client's working directory.
   */
  files?: string[] // biomejs (../src/index.ts:58:13)
}

export type ClientBiomejsOpts = {
  /**
   * The base image to use.
   * 
   * This assume biome will run in a node container using npm
   * as package manager.
   */
  baseImageAddress: string // biomejs (../src/index.ts:33:3)
}


export class Biomejs extends BaseClient { // biomejs (../src/index.ts:17:14)
  private readonly _id?: ID | undefined = undefined
  private readonly _path?: string | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _path?: string,
   ) {
     super(ctx)

     this._id = _id
     this._path = _path
   }

  /**
   * A unique identifier for this Biomejs.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Fix lint issue and return a changeset of the result.
   * @param opts.files Files to apply fix on, relative to the client's working directory.
   * @param opts.fixFilter Patterns to select files to include in the changeset.
   */
  fix = (opts?: BiomejsFixOpts // biomejs (../src/index.ts:72:8) 
		): Changeset => { // biomejs (../src/index.ts:72:8)

    const ctx = this._ctx.select(
      "fix",
      { ...opts },
    )
    return new Changeset(ctx)
  }

  /**
   * Lint the source code.
   * @param opts.files Files to lint, relative to the client's working directory.
   */
  lint = (opts?: BiomejsLintOpts // biomejs (../src/index.ts:58:8) 
		): Check => { // biomejs (../src/index.ts:58:8)

    const ctx = this._ctx.select(
      "lint",
      { ...opts },
    )
    return new Check(ctx)
  }

  /**
   * Path of the client's working directory, relative to the workspace root.
   */
  path = async (): Promise<string> => { // biomejs (../src/index.ts:44:8)
    if (this._path) {
      return this._path
    }

    const ctx = this._ctx.select(
      "path",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
}

/**
 * The root of the DAG.
 */
export class Client extends BaseClient {

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
   ) {
     super(ctx)

   }

  /**
   * Get the Raw GraphQL client.
   */
  public getGQLClient() {
    return this._ctx.getGQLClient()
  }

  /**
   * A BiomeJS toolchain to execute Biome on a JavaScript project.
   * @param opts.baseImageAddress The base image to use.
   * 
   * This assume biome will run in a node container using npm
   * as package manager.
   */
  biomejs = (ws: Workspace, opts?: ClientBiomejsOpts // biomejs (../:0:0) 
		): Biomejs => { // biomejs (../:0:0)

    const ctx = this._ctx.select(
      "biomejs",
      { ws, ...opts },
    )
    return new Biomejs(ctx)
  }
}



async function __serveModule(): Promise<void> {
  await __dag.serveModule("/.")
}

export const dag = new Client(
  new Context().withServe({ key: "biomejs", run: __serveModule }),
)
export function biomejs(ws: Workspace, opts?: ClientBiomejsOpts): Biomejs {
  return dag.biomejs(ws, opts)
}
