/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */

import { Context, BaseClient } from "./core.js"
import {
  Changeset
} from "./client.gen.js"
import type {
  ID,
  Void
} from "./client.gen.js"


export type BiomejsFixOpts = {
  /**
   * Files to apply fix on, relative to the client's working directory.
   */
  files?: string[] // biomejs (../src/index.ts:73:3)

  /**
   * Patterns to select files to include in the changeset.
   */
  fixFilter?: string[] // biomejs (../src/index.ts:74:3)
}

export type BiomejsLintOpts = {
  /**
   * Files to lint, relative to the client's working directory.
   */
  files?: string[] // biomejs (../src/index.ts:58:13)
}

export type ClientBiomejsOpts = {
  /**
   * The base image to use.
   * 
   * This assume biome will run in a node container using npm
   * as package manager.
   */
  baseImageAddress: string // biomejs (../src/index.ts:33:3)
}


export class Biomejs extends BaseClient { // biomejs (../src/index.ts:17:14)
  private readonly _id?: ID = undefined
  private readonly _lint?: Void = undefined
  private readonly _path?: string = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _lint?: Void,
     _path?: string,
   ) {
     super(ctx)

     this._id = _id
     this._lint = _lint
     this._path = _path
   }

  /**
   * A unique identifier for this Biomejs.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Fix lint issue and return a changeset of the result.
   * @param opts.files Files to apply fix on, relative to the client's working directory.
   * @param opts.fixFilter Patterns to select files to include in the changeset.
   */
  fix = (opts?: BiomejsFixOpts // biomejs (../src/index.ts:72:8) 
		): Changeset => { // biomejs (../src/index.ts:72:8)

    const ctx = this._ctx.select(
      "fix",
      { ...opts },
    )
    return new Changeset(ctx)
  }

  /**
   * Lint the source code.
   * @param opts.files Files to lint, relative to the client's working directory.
   */
  lint = async (
    opts?: BiomejsLintOpts // biomejs (../src/index.ts:58:8) 
    ): Promise<void> => { // biomejs (../src/index.ts:58:8)
    if (this._lint) {
      return
    }

    const ctx = this._ctx.select(
      "lint",
      { ...opts},
    )

    await ctx.execute()

    
  }

  /**
   * Path of the client's working directory, relative to the workspace root.
   */
  path = async (): Promise<string> => { // biomejs (../src/index.ts:44:8)
    if (this._path) {
      return this._path
    }

    const ctx = this._ctx.select(
      "path",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
}


declare module "./client.gen.js" {
  interface Client {
    biomejs(ws: Workspace, opts?: ClientBiomejsOpts): Biomejs
  }
}

import type {
  Client as __Client
} from "./client.gen.js"

export function __applyBiomejsAugmentations(scope: {
  Client: typeof __Client
}) {
  const { Client } = scope
  type Client = __Client

Client.prototype.biomejs = function (this: any, ws: Workspace, opts?: ClientBiomejsOpts): Biomejs {

    const ctx = this._ctx.select(
      "biomejs",
      { ws, ...opts },
    )
    return new Biomejs(ctx)
}
}