/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context, BaseClient } from "@dagger.io/dagger"
import { dag as __dag } from "@dagger.io/dagger"
import {
  Changeset,
  Check,
  Workspace
} from "@dagger.io/dagger"
import type {
  ID
} from "@dagger.io/dagger"


export type BiomejsBiomeProjectFixOpts = {
  /**
   * Files to fix, relative to the project root.
   */
  files?: string[] // biomejs (../src/index.ts:213:3)

  /**
   * Patterns, relative to the project root, of files to include in the changeset.
   */
  fixFilter?: string[] // biomejs (../src/index.ts:214:3)
}

export type ClientBiomejsOpts = {
  /**
   * The base image to use.
   * 
   * This assume biome will run in a node container using npm
   * as package manager.
   */
  baseImageAddress: string // biomejs (../src/index.ts:337:3)
}


export class Biomejs extends BaseClient { // biomejs (../src/index.ts:327:14)
  private readonly _id?: ID | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
   ) {
     super(ctx)

     this._id = _id
   }

  /**
   * A unique identifier for this Biomejs.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Biome projects at or below the working directory, keyed by project root.
   */
  projects = (ws: Workspace): BiomejsBiomeProjects => { // biomejs (../src/index.ts:346:8)

    const ctx = this._ctx.select(
      "projects",
      { ws },
    )
    return new BiomejsBiomeProjects(ctx)
  }
}

/**
 * A Biome project, rooted at a workspace-relative directory holding a root
 * Biome configuration.
 */
export class BiomejsBiomeProject extends BaseClient { // biomejs (../src/index.ts:178:14)
  private readonly _id?: ID | undefined = undefined
  private readonly _path?: string | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _path?: string,
   ) {
     super(ctx)

     this._id = _id
     this._path = _path
   }

  /**
   * A unique identifier for this BiomejsBiomeProject.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Fix lint issues in this project and return the changes, rooted at the
   * workspace root.
   * @param opts.files Files to fix, relative to the project root.
   * @param opts.fixFilter Patterns, relative to the project root, of files to include in the changeset.
   */
  fix = (ws: Workspace, opts?: BiomejsBiomeProjectFixOpts // biomejs (../src/index.ts:211:8) 
		): Changeset => { // biomejs (../src/index.ts:211:8)

    const ctx = this._ctx.select(
      "fix",
      { ws, ...opts },
    )
    return new Changeset(ctx)
  }

  /**
   * Lint this project.
   */
  lint = (ws: Workspace): Check => { // biomejs (../src/index.ts:197:8)

    const ctx = this._ctx.select(
      "lint",
      { ws },
    )
    return new Check(ctx)
  }

  /**
   * Project root, relative to the workspace.
   */
  path = async (): Promise<string> => { // biomejs (../src/index.ts:183:2)
    if (this._path) {
      return this._path
    }

    const ctx = this._ctx.select(
      "path",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
}

/**
 * Biome projects in a workspace, keyed by the directory of their root Biome
 * configuration.
 */
export class BiomejsBiomeProjects extends BaseClient { // biomejs (../src/index.ts:280:14)
  private readonly _id?: ID | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
   ) {
     super(ctx)

     this._id = _id
   }

  /**
   * A unique identifier for this BiomejsBiomeProjects.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Operations on the current collection.
   */
  batch = (): BiomejsBiomeProjects_Batch => {

    const ctx = this._ctx.select(
      "batch",
    )
    return new BiomejsBiomeProjects_Batch(ctx)
  }

  /**
   * The Biome project rooted at path.
   */
  get = (key: string): BiomejsBiomeProject => { // biomejs (../src/index.ts:298:2)

    const ctx = this._ctx.select(
      "get",
      { key },
    )
    return new BiomejsBiomeProject(ctx)
  }

  /**
   * Current keys, in author order.
   */
  keys = async (): Promise<string[]> => {
    const ctx = this._ctx.select(
      "keys",
    )

    const response: Awaited<string[]> = await ctx.execute()

    
    return response
  }

  /**
   * Items in the same order as keys.
   */
  list = async (): Promise<BiomejsBiomeProject[]> => {
    type list = {
      id: ID
    }

    const ctx = this._ctx.select(
      "list",
    ).select("id")

    const response: Awaited<list[]> = await ctx.execute()

    
    return response.map((r) => new BiomejsBiomeProject(ctx.copy().selectNode(r.id, "BiomejsBiomeProject")))
  }

  /**
   * Select keys from this collection. Preserve author order.
   */
  subset = (keys: string[]): BiomejsBiomeProjects => {

    const ctx = this._ctx.select(
      "subset",
      { keys },
    )
    return new BiomejsBiomeProjects(ctx)
  }

  /**
   * Call the provided function with current BiomejsBiomeProjects.
   *
   * This is useful for reusability and readability by not breaking the calling chain.
   */
  with = (arg: (param: BiomejsBiomeProjects) => BiomejsBiomeProjects) => {
    return arg(this)
  }
}

/**
 * Biome projects in a workspace, keyed by the directory of their root Biome
 * configuration.
 */
export class BiomejsBiomeProjects_Batch extends BaseClient { // biomejs (../src/index.ts:280:14)
  private readonly _id?: ID | undefined = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
   ) {
     super(ctx)

     this._id = _id
   }

  /**
   * A unique identifier for this BiomejsBiomeProjects_Batch.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Lint the selected Biome projects.
   */
  lint = (ws: Workspace): Check => { // biomejs (../src/index.ts:307:8)

    const ctx = this._ctx.select(
      "lint",
      { ws },
    )
    return new Check(ctx)
  }
}

/**
 * The root of the DAG.
 */
export class Client extends BaseClient {

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
   ) {
     super(ctx)

   }

  /**
   * Get the Raw GraphQL client.
   */
  public getGQLClient() {
    return this._ctx.getGQLClient()
  }

  /**
   * A BiomeJS toolchain to execute Biome on a JavaScript project.
   * @param opts.baseImageAddress The base image to use.
   * 
   * This assume biome will run in a node container using npm
   * as package manager.
   */
  biomejs = (opts?: ClientBiomejsOpts // biomejs (../:0:0) 
		): Biomejs => { // biomejs (../:0:0)

    const ctx = this._ctx.select(
      "biomejs",
      { ...opts },
    )
    return new Biomejs(ctx)
  }
}



async function __serveModule(): Promise<void> {
  await __dag.serveModule("/.")
}

export const dag = new Client(
  new Context().withServe({ key: "biomejs", run: __serveModule }),
)
export function biomejs(opts?: ClientBiomejsOpts): Biomejs {
  return dag.biomejs(opts)
}
