/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context } from "@dagger.io/dagger"
import * as __core from "@dagger.io/dagger"
import * as __modBiomejs from "@dagger.io/biomejs"

const __classes: Record<string, any> = {
  "Address": __core.Address,
  "Agent": __core.Agent,
  "AgentMessage": __core.AgentMessage,
  "Artifact": __core.Artifact,
  "ArtifactDimension": __core.ArtifactDimension,
  "ArtifactDimensionKey": __core.ArtifactDimensionKey,
  "ArtifactPath": __core.ArtifactPath,
  "ArtifactResult": __core.ArtifactResult,
  "Artifacts": __core.Artifacts,
  "CacheVolume": __core.CacheVolume,
  "Changeset": __core.Changeset,
  "Check": __core.Check,
  "ClientFilesyncMirror": __core.ClientFilesyncMirror,
  "Cloud": __core.Cloud,
  "CollectionDelta": __core.CollectionDelta,
  "CollectionTypeDef": __core.CollectionTypeDef,
  "Command": __core.Command,
  "Container": __core.Container,
  "CurrentModule": __core.CurrentModule,
  "DiffStat": __core.DiffStat,
  "Directory": __core.Directory,
  "EnumTypeDef": __core.EnumTypeDef,
  "EnumValueTypeDef": __core.EnumValueTypeDef,
  "EnvFile": __core.EnvFile,
  "EnvVariable": __core.EnvVariable,
  "Error": __core.Error,
  "ErrorValue": __core.ErrorValue,
  "Expertise": __core.Expertise,
  "FieldTypeDef": __core.FieldTypeDef,
  "File": __core.File,
  "Function": __core.Function_,
  "FunctionArg": __core.FunctionArg,
  "FunctionCall": __core.FunctionCall,
  "FunctionCallArgValue": __core.FunctionCallArgValue,
  "GeneratedCode": __core.GeneratedCode,
  "Generator": __core.Generator,
  "GitBundle": __core.GitBundle,
  "GitBundleRef": __core.GitBundleRef,
  "GitCommit": __core.GitCommit,
  "GitPushResult": __core.GitPushResult,
  "GitRef": __core.GitRef,
  "GitRepository": __core.GitRepository,
  "HTTPState": __core.HTTPState,
  "HealthcheckConfig": __core.HealthcheckConfig,
  "InputTypeDef": __core.InputTypeDef,
  "InterfaceTypeDef": __core.InterfaceTypeDef,
  "JSONValue": __core.JSONValue,
  "LLM": __core.LLM,
  "LLMContentBlock": __core.LLMContentBlock,
  "LLMMessage": __core.LLMMessage,
  "LLMMessageOrigin": __core.LLMMessageOrigin,
  "LLMSkill": __core.LLMSkill,
  "LLMTokenUsage": __core.LLMTokenUsage,
  "Label": __core.Label,
  "ListTypeDef": __core.ListTypeDef,
  "Module": __core.Module_,
  "ModuleConfigClient": __core.ModuleConfigClient,
  "ModuleSource": __core.ModuleSource,
  "ObjectTypeDef": __core.ObjectTypeDef,
  "Port": __core.Port,
  "RemoteGitMirror": __core.RemoteGitMirror,
  "SDKConfig": __core.SDKConfig,
  "ScalarTypeDef": __core.ScalarTypeDef,
  "Schema": __core.Schema,
  "SearchResult": __core.SearchResult,
  "SearchSubmatch": __core.SearchSubmatch,
  "Secret": __core.Secret,
  "Service": __core.Service,
  "Socket": __core.Socket,
  "SourceMap": __core.SourceMap,
  "Stat": __core.Stat,
  "Terminal": __core.Terminal,
  "TypeDef": __core.TypeDef,
  "Volume": __core.Volume,
  "Workspace": __core.Workspace,
  "WorkspaceCommitPick": __core.WorkspaceCommitPick,
  "WorkspaceGit": __core.WorkspaceGit,
  "WorkspaceMigration": __core.WorkspaceMigration,
  "WorkspaceMigrationStep": __core.WorkspaceMigrationStep,
  "WorkspaceModule": __core.WorkspaceModule,
  "WorkspaceModuleSetting": __core.WorkspaceModuleSetting,
  "WorkspaceSDK": __core.WorkspaceSDK,
  "Biomejs": __modBiomejs.Biomejs,
}

// Load a core object from its ID via node(id:) and wrap it in the matching
// generated client class. Only core types reach this: a module's exposed
// signatures use core types or its own types, never a dependency's, so the
// engine always has the type served and no lazy serve is needed here. Replaces
// the retired load<Type>FromID API (removed in #12041).
export function __loadObject(id: string, typeName: string): any {
  const cls = __classes[typeName]
  if (!cls) {
    throw new Error(`generated client class not found for type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}